{
 "title": "CipherTrust Manager Resources",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instances", "label": "instances", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Total  Users in the System",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ciphertrust_user_management_total_users{instance =~ \"$instances\"}",
     "legendFormat": "Total Users across the System"
    }
   ]
  },
  {
   "title": "Group Users in the System",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ciphertrust_user_management_group_users{instance =~ \"$instances\"}",
     "legendFormat": "Users in group : {{group}}"
    }
   ]
  },
  {
   "title": "Total Number Of Connector Licenses Deployed",
   "type": "table",
   "description": "Represents the count of connector licenses currently present in the system categorized according to their states (active/inactive). \nAlso shows the total license units which can be created for a particular feature.\nThe license unit count for:  \nDDC represents: maximum data allowance in TBs.  \nCCKM represents: maximum no. of cloud connections that can be added.  \nOthers: client units.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ciphertrust_license_manager_number_of_active_connector_licenses{instance =~ \"$instances\"}"
    },
    {
     "expr": "sum(ciphertrust_license_manager_number_of_inactive_connector_licenses{instance =~ \"$instances\"}) without (__name__)"
    },
    {
     "expr": "sum(ciphertrust_license_manager_total_number_of_license_units{instance =~ \"$instances\"}) without (__name__)"
    }
   ]
  },
  {
   "title": "Number of License Units Consumed",
   "type": "graph",
   "description": "Represents number of consumed license units for a particular feature.\nThe license unit count for:  \nDDC represents: data usage in TBs.  \nCCKM represents: no. of cloud connections.  \nothers: client units.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ciphertrust_license_manager_number_of_consumed_license_units{instance =~ \"$instances\"}",
     "legendFormat": "{{instance}} / Type: {{feature}}"
    }
   ]
  },
  {
   "title": "Audit Records Created Per Second Over The Last Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ciphertrust_audit_log_client_logs_total{instance =~ \"$instances\", service = \"audit_log\"}[1m])",
     "legendFormat": "{{instance}} / client"
    },
    {
     "expr": "rate(ciphertrust_audit_log_records_total{instance =~ \"$instances\", service = \"audit_log\"}[1m])",
     "legendFormat": "{{instance}} / server"
    }
   ]
  },
  {
   "title": "License Unit Consumption by Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(ciphertrust_license_manager_number_of_consumed_license_units{instance =~ \"$instances\"} / ciphertrust_license_manager_total_number_of_license_units{instance =~ \"$instances\"}) * 100",
     "legendFormat": "{{instance}}  / {{feature}}"
    }
   ]
  },
  {
   "title": "Total Number Of Audit Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ciphertrust_audit_log_client_logs_total{instance =~ \"$instances\", service = \"audit_log\"}",
     "legendFormat": "{{instance}} / client"
    },
    {
     "expr": "ciphertrust_audit_log_records_total{instance =~ \"$instances\", service = \"audit_log\"}",
     "legendFormat": "{{instance}} / server"
    }
   ]
  },
  {
   "title": "Audit Records Created In Last Five Minutes",
   "type": "graph",
   "description": "This panel gives information about the trend of Audit Records. Please note that these are NOT absolute figures.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ciphertrust_audit_log_client_logs_total{instance =~ \"$instances\", service = \"audit_log\"}[5m])",
     "legendFormat": "{{instance}} / client"
    },
    {
     "expr": "increase(ciphertrust_audit_log_records_total{instance =~ \"$instances\", service = \"audit_log\"}[5m])",
     "legendFormat": "{{instance}} / server"
    }
   ]
  },
  {
   "title": "Total Number Of Keys By Algorithm",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "ciphertrust_key_vault_deks_total",
     "legendFormat": "{{algorithm}} "
    }
   ]
  },
  {
   "title": "Crypto Operations Per Second Over The Last Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_response_time_seconds_count{instance =~ \"$instances\", code = \"200\", method = \"POST\", path = \"/encrypt\", service = \"crypto\"}[1m])",
     "legendFormat": "{{instance}} / Encryptions"
    },
    {
     "expr": "rate(http_response_time_seconds_count{instance =~ \"$instances\", code = \"200\", method = \"POST\", path = \"/decrypt\", service = \"crypto\"}[1m])",
     "legendFormat": "{{instance}} / Decryptions"
    }
   ]
  },
  {
   "title": "Total Number Of Key Rotations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "ciphertrust_key_vault_key_rotations{instance =~ \"$instances\", source = \"scheduler\"}"
    },
    {
     "expr": "ciphertrust_key_vault_key_rotations{instance =~ \"$instances\", source != \"scheduler\"}"
    }
   ]
  },
  {
   "title": "Key Rotations In Last Five Minutes",
   "type": "graph",
   "description": "This panel gives information about the trend of Key-Rotations. Please note that these are NOT absolute figures.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ciphertrust_key_vault_key_rotations{instance =~ \"$instances\", source != \"scheduler\"}[5m])",
     "legendFormat": "{{instance}} / {{source}}"
    },
    {
     "expr": "increase(ciphertrust_key_vault_key_rotations{instance =~ \"$instances\", source = \"scheduler\"}[5m])",
     "legendFormat": "{{instance}} / scheduler job: {{job_name}} expired: {{expired}}"
    }
   ]
  },
  {
   "title": "Time Taken To Create Backup",
   "type": "graph",
   "description": "This panel gives information about the trend of backup creation time. Please note that these are NOT absolute figures.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase(ciphertrust_backup_number_of_backups_taken_sum{instance =~ \"$instances\"}[1m]) / increase(ciphertrust_backup_number_of_backups_taken_count{instance =~ \"$instances\"}[1m]))",
     "legendFormat": "{{instance}} / {{scope}}"
    }
   ]
  },
  {
   "title": "Number of Backups Taken",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "ciphertrust_backup_number_of_backups_taken_count{instance =~ \"$instances\"}",
     "legendFormat": "{{instance}} / {{scope}} status: {{status}}"
    }
   ]
  },
  {
   "title": "Total Number of Keys by States and Algorithm",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "ciphertrust_key_vault_deks_total",
     "legendFormat": "{{algorith}}"
    }
   ]
  }
 ]
}