{
 "title": "CipherTrust Manager CTE Resources",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instances", "label": "instances", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "CTE Clients",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ciphertrust_cte_management_cte_clients{instance =~ \"$instances\"}",
     "legendFormat": "{{clients_type}}"
    }
   ]
  },
  {
   "title": "CTE Clients Health Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ciphertrust_cte_management_clients_health_status{instance =~ \"$instances\"}",
     "legendFormat": "{{health_status}}"
    }
   ]
  },
  {
   "title": "CTE Groups",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ciphertrust_cte_management_cte_groups{instance =~ \"$instances\"}",
     "legendFormat": "{{group_name}}"
    }
   ]
  },
  {
   "title": "CTE Guard Points State",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(guard_state) (ciphertrust_cte_management_cte_guardpoints{instance =~ \"$instances\"})",
     "legendFormat": "{{guard_state}}"
    }
   ]
  }
 ]
}