{
 "title": "CipherTrust Manager Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instances", "label": "instances", "query": { "query": "label_values(instance)" } },
   { "name": "job", "query": { "query": "label_values(job)" } },
   { "name": "nodes", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  {
   "title": "Cluster Metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "sum by (instance,job,host) (ciphertrust_cluster_connected{instance=~\"$instances\", job=~\"$job\", host=~\"$nodes\"})"
    },
    {
     "expr": "sum by (instance,job,host) (ciphertrust_cluster_replication_blocked{instance=~\"$instances\", job=~\"$job\", host=~\"$nodes\"})"
    },
    {
     "expr": "sum by (instance,job,host) (ciphertrust_cluster_connect_time{instance=~\"$instances\", job=~\"$job\", host=~\"$nodes\"})*1000"
    },
    {
     "expr": "sum by (instance,job,host) (ciphertrust_cluster_uptime{instance=~\"$instances\", job=~\"$job\", host=~\"$nodes\"})"
    }
   ]
  },
  {
   "title": "Write Lag",
   "type": "graph",
   "description": "Approximate lag time for reported write",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "ciphertrust_cluster_write_lag{instance =~ \"$instances\", job=~\"$job\", host=~\"$nodes\"}",
     "legendFormat": "Origin Node: {{instance}}, Target Node: {{host}}"
    }
   ]
  },
  {
   "title": "Flush Lag",
   "type": "graph",
   "description": "Approximate lag time for reported flush",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "ciphertrust_cluster_flush_lag{instance =~ \"$instances\", job=~\"$job\", host=~\"$nodes\"}",
     "legendFormat": "Origin Node: {{instance}}, Target Node: {{host}}"
    }
   ]
  },
  {
   "title": "Replay Lag",
   "type": "graph",
   "description": "Approximate lag time for reported replay",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "ciphertrust_cluster_replay_lag{instance =~ \"$instances\", job=~\"$job\", host=~\"$nodes\"}",
     "legendFormat": "Origin Node: {{instance}}, Target Node: {{host}}"
    }
   ]
  },
  {
   "title": "Sent Lag Bytes",
   "type": "graph",
   "description": "Bytes difference between sent_lsn and current WAL write position",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "ciphertrust_cluster_sent_lag_bytes{instance =~ \"$instances\", job=~\"$job\", host=~\"$nodes\"}",
     "legendFormat": "Origin Node: {{instance}}, Target Node: {{host}}"
    }
   ]
  },
  {
   "title": "Write Lag Bytes",
   "type": "graph",
   "description": "Bytes difference between write_lsn and current WAL write position",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "ciphertrust_cluster_write_lag_bytes{instance =~ \"$instances\", job=~\"$job\", host=~\"$nodes\"}",
     "legendFormat": "Origin Node: {{instance}}, Target Node: {{host}}"
    }
   ]
  },
  {
   "title": "Flush Lag Bytes",
   "type": "graph",
   "description": "Bytes difference between flush_lsn and current WAL write position",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "ciphertrust_cluster_flush_lag_bytes{instance =~ \"$instances\", job=~\"$job\", host=~\"$nodes\"}",
     "legendFormat": "Origin Node: {{instance}}, Target Node: {{host}}"
    }
   ]
  },
  {
   "title": "Replay Lag Bytes",
   "type": "graph",
   "description": "Bytes difference between replay_lsn and current WAL write position on origin",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "ciphertrust_cluster_replay_lag_bytes{instance =~ \"$instances\", job=~\"$job\", host=~\"$nodes\"}",
     "legendFormat": "Origin Node: {{instance}}, Target Node: {{host}}"
    }
   ]
  },
  {
   "title": "Catchup Interval",
   "type": "graph",
   "description": "Approximate time required for the peer node to catch up to all the changes that are yet to be applied",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "ciphertrust_cluster_catchup_interval{instance =~ \"$instances\", job=~\"$job\", host=~\"$nodes\"}",
     "legendFormat": "Origin Node: {{instance}}, Target Node: {{host}}"
    }
   ]
  },
  {
   "title": "Apply Rate",
   "type": "graph",
   "description": "LSNs being applied per second at the peer node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "LSN/s" }
   ],
   "targets": [
    {
     "expr": "ciphertrust_cluster_apply_rate{instance =~ \"$instances\", job=~\"$job\", host=~\"$nodes\"}",
     "legendFormat": "Origin Node: {{instance}}, Target Node: {{host}}"
    }
   ]
  }
 ]
}