{
 "title": "Akeyless-Gateway",
 "description": "The Akeyless Vault Platform is a unified secrets management system that enables you to store, protect, rotate, and dynamically create credentials, certificates, and encryption keys.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "host", "label": "host", "query": { "query": "label_values(akeyless)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance_id)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "### The [Akeyless Vault Platform](www.akeyless.io) is a unified secrets management system that enables you to store, protect, rotate, and dynamically create credentials, certificates, and encryption keys.\n\n#### - [Official Akeyless docs](https://docs.akeyless.io/)\n#### - [Monitoring Akeyless With Prometheus](https://docs.akeyless.io/docs/telemetry-metrics)\n"
   }
  },
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (akeyless_gw_system_cpu_usage_percent)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "GW Current Transactions Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg(akeyless_gw_quota_current_transactions_number) by (account_id,access_id)"
    }
   ]
  },
  {
   "title": "GW Admin Client Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 5 },
   "targets": [
    {
     "expr": "avg(akeyless_gw_quota_gw_admin_client_transactions) by (access_id,account_id)"
    }
   ]
  },
  {
   "title": "GW Transactions Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(akeyless_gw_quota_current_transactions_number) / avg(akeyless_gw_quota_total_transactions_limit) "
    }
   ]
  },
  {
   "title": "Total Transactions Limit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(akeyless_gw_quota_total_transactions_limit) "
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Processes CPU Usage % ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(akeyless_gw_system_cpu_usage_percent{akeyless=~\"$host$\", instance_id=~\"$instance$\"}) by (akeyless,instance_id)",
     "legendFormat": "{{akeyless}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Host Machine CPU Load Average 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "avg(akeyless_gw_system_cpu_load_average_1m_ratio{akeyless=~\"$host$\", instance_id=~\"$instance$\"}) by (akeyless,instance_id)",
     "legendFormat": "{{akeyless}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Host Machine CPU Load Average 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "avg(akeyless_gw_system_cpu_load_average_5m_ratio{akeyless=~\"$host$\", instance_id=~\"$instance$\"}) by (akeyless,instance_id)",
     "legendFormat": "{{akeyless}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Host Machine CPU Load Average 15m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "avg(akeyless_gw_system_cpu_load_average_15m_ratio{akeyless=~\"$host$\", instance_id=~\"$instance$\"}) by (akeyless,instance_id)",
     "legendFormat": "{{akeyless}} ({{instance_id}})"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg (akeyless_gw_system_memory_usage_in_bytes{akeyless=~\"$host$\", instance_id=~\"$instance$\"}) by (akeyless,instance_id)",
     "legendFormat": "{{akeyless}} ({{instance_id}})"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Bytes rx ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg (akeyless_gw_system_network_io_receive_bytes{akeyless=~\"$host$\", instance_id=~\"$instance$\"}) by (akeyless,instance_id)",
     "legendFormat": "{{akeyless}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "Bytes tx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg (akeyless_gw_system_network_io_transmit_bytes{akeyless=~\"$host$\", instance_id=~\"$instance$\"}) by (akeyless,instance_id)",
     "legendFormat": "{{akeyless}} ({{instance_id}})"
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "I/O read ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg (akeyless_gw_system_disk_io_read_bytes{akeyless=~\"$host$\", instance_id=~\"$instance$\"}) by (akeyless,instance_id)",
     "legendFormat": "{{akeyless}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "I/O read ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg (akeyless_gw_system_disk_io_read_bytes{akeyless=~\"$host$\", instance_id=~\"$instance$\"}) by (akeyless,instance_id)",
     "legendFormat": "{{akeyless}} ({{instance_id}})"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "rate(akeyless_gw_system_request_count_total{akeyless=~\"$host$\", instance_id=~\"$instance$\"}[1m])",
     "legendFormat": "{{akeyless}} ({{instance_id}})"
    }
   ]
  },
  {
   "title": "HTTP Response by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "rate(akeyless_gw_system_http_response_status_code_total{akeyless=~\"$host$\", instance_id=~\"$instance$\"}[1m])",
     "legendFormat": "{{akeyless}} ({{instance_id}}) {{status}}"
    }
   ]
  }
 ]
}