{
 "title": "CipherTrust Manager NAE",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instances", "label": "instances", "query": { "query": "label_values(instance)" } },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "NAE-XML Operations",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "floor(increase(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\"}[$__range]))"
    },
    {
     "expr": "sum(floor(increase(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\"}[$__range]))) without(_name_)"
    }
   ]
  },
  {
   "title": "Rate of Operations",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Authenticate\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Authenticate\"}[$__rate_interval]))",
     "legendFormat": "Authenticate"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Generate\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Generate\"}[$__rate_interval]))",
     "legendFormat": "Key Generate"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Version Generate\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Version Generate\"}[$__rate_interval]))",
     "legendFormat": "Key Version Generate"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Delete\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Delete\"}[$__rate_interval]))",
     "legendFormat": "Key Delete"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Information\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Information\"}[$__rate_interval]))",
     "legendFormat": "Key Information"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Query\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Query\"}[$__rate_interval]))",
     "legendFormat": "Key Query"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Import\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Import\"}[$__rate_interval]))",
     "legendFormat": "Key Import"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Export\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Export\"}[$__rate_interval]))",
     "legendFormat": "Key Export"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Modify\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Modify\"}[$__rate_interval]))",
     "legendFormat": "Key Modify"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Version Modify\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Version Modify\"}[$__rate_interval]))",
     "legendFormat": "Key Version Modify"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Clone\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Clone\"}[$__rate_interval]))",
     "legendFormat": "Key Clone"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Public Key Export\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Public Key Export\"}[$__rate_interval]))",
     "legendFormat": "Public Key Export"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Certificate Export\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Certificate Export\"}[$__rate_interval]))",
     "legendFormat": "Certificate Export"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"CA Export\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"CA Export\"}[$__rate_interval]))",
     "legendFormat": "CA Export"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Certificate Export\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Certificate Export\"}[$__rate_interval]))",
     "legendFormat": "Key Certificate Export"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Random Generate\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Random Generate\"}[$__rate_interval]))",
     "legendFormat": "Random Generate"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Record Event\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Record Event\"}[$__rate_interval]))",
     "legendFormat": "Record Event"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"CSR Create\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"CSR Create\"}[$__rate_interval]))",
     "legendFormat": "CSR Create"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Certificate Request Sign\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Certificate Request Sign\"}[$__rate_interval]))",
     "legendFormat": "Certificate Request Sign "
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Version Import\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Version Import\"}[$__rate_interval]))",
     "legendFormat": "Key Version Import"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Cryptographic Operation\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Cryptographic Operation\"}[$__rate_interval]))",
     "legendFormat": "Cryptographic Operation"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Names\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Names\"}[$__rate_interval]))",
     "legendFormat": "Key Names"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_nae_key_management_operation_success{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Usage\"}[$__rate_interval]) + rate(ciphertrust_nae_nae_key_management_operation_failure{instance =~ \"$instances\", job=~\"$job\", operation =~ \"Key Usage\"}[$__rate_interval]))",
     "legendFormat": "Key Usage"
    }
   ]
  },
  {
   "title": "XML Response Time",
   "type": "timeseries",
   "description": "Total time to read a request and respond to it.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "(rate(ciphertrust_nae_xml_response_time_seconds_sum{instance =~ \"$instances\" ,job =~ \"$job\"}[1m]) / rate(ciphertrust_nae_xml_response_time_seconds_count{instance =~ \"$instances\" ,job =~ \"$job\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "XML Processing Time",
   "type": "timeseries",
   "description": "Time to process a NAE XML request (excludes time reading/parsing request, and excludes time sending response)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "(rate(ciphertrust_nae_xml_processing_time_seconds_sum{instance =~ \"$instances\", job =~ \"$job\"}[1m]) / rate(ciphertrust_nae_xml_processing_time_seconds_count{instance =~ \"$instances\", job =~ \"$job\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}