{
 "title": "CipherTrust Manager KMIP Key Management Metrics",
 "description": "Metrics & graphs to record total and rate of operation for successful and failed KMIP key managemet operations.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instances", "label": "instances", "query": { "query": "label_values(instance)" } },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Successful Operations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ciphertrust_nae_kmip_create_key_pair_success{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Create Key Pair"
    },
    {
     "expr": "ciphertrust_nae_kmip_add_attribute_success{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Add Attribute"
    },
    {
     "expr": "ciphertrust_nae_kmip_create_success{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Create"
    },
    {
     "expr": "ciphertrust_nae_kmip_get_attributes_success{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Get Attribute"
    },
    {
     "expr": "ciphertrust_nae_kmip_modify_attribute_success{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Modify Attribute"
    },
    {
     "expr": "ciphertrust_nae_kmip_revoke_success{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Revoke"
    },
    {
     "expr": "ciphertrust_nae_kmip_delete_attribute_success{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Delete  Atrribute"
    },
    {
     "expr": "ciphertrust_nae_kmip_check_success{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Check"
    },
    {
     "expr": "ciphertrust_nae_kmip_get_attribute_list_success{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Get Attribute List"
    },
    {
     "expr": "ciphertrust_nae_kmip_get_success{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Get"
    },
    {
     "expr": "ciphertrust_nae_kmip_locate_success{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Locate"
    },
    {
     "expr": "ciphertrust_nae_kmip_discover_versions_success{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Discover Version"
    },
    {
     "expr": "ciphertrust_nae_kmip_activate_success{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Activate"
    },
    {
     "expr": "ciphertrust_nae_kmip_query_success{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Query"
    },
    {
     "expr": "ciphertrust_nae_kmip_destroy_success{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Destroy"
    },
    {
     "expr": "ciphertrust_nae_kmip_register_success{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Register"
    }
   ]
  },
  {
   "title": "Rate of Successful Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_create_key_pair_success{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Create Key Pair "
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_add_attribute_success{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Add Attribute"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_create_success{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_get_attributes_success{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Get Attribute "
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_modify_attribute_success{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Modify Attribute "
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_revoke_success{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Revoke"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_delete_attribute_success{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Delete  Atrribute"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_check_success{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Check "
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_get_attribute_list_success{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Get Attribute List "
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_get_success{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Get"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_locate_success{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Locate"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_discover_versions_success{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Discover Version"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_activate_success{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Activate "
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_query_success{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Query "
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_destroy_success{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Destroy"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_register_success{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Register "
    }
   ]
  },
  {
   "title": "Failed Operations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ciphertrust_nae_kmip_create_key_pair_failure{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Create Key Pair"
    },
    {
     "expr": "ciphertrust_nae_kmip_add_attribute_failure{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Add Attribute"
    },
    {
     "expr": "ciphertrust_nae_kmip_create_failure{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Create"
    },
    {
     "expr": "ciphertrust_nae_kmip_get_attributes_failure{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Get Attributes"
    },
    {
     "expr": "ciphertrust_nae_kmip_modify_attribute_failure{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Modify Attribute"
    },
    {
     "expr": "ciphertrust_nae_kmip_revoke_failure{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Revoke"
    },
    {
     "expr": "ciphertrust_nae_kmip_delete_attribute_failure{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Delete Attribute"
    },
    {
     "expr": "ciphertrust_nae_kmip_check_failure{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Check"
    },
    {
     "expr": "ciphertrust_nae_kmip_get_attribute_list_failure{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Get Attribute List"
    },
    {
     "expr": "ciphertrust_nae_kmip_get_failure{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Get Failure"
    },
    {
     "expr": "ciphertrust_nae_kmip_locate_failure{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Locate"
    },
    {
     "expr": "ciphertrust_nae_kmip_discover_versions_failure{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Discover Versions"
    },
    {
     "expr": "ciphertrust_nae_kmip_activate_failure{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Activate"
    },
    {
     "expr": "ciphertrust_nae_kmip_query_failure{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Query"
    },
    {
     "expr": "ciphertrust_nae_kmip_destroy_failure{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Destroy"
    },
    {
     "expr": "ciphertrust_nae_kmip_register_failure{instance=~\"$instances\", job=~\"$job\"}",
     "legendFormat": "Register"
    }
   ]
  },
  {
   "title": "Rate of Failed Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_create_key_pair_failure{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Create Key Pair"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_add_attribute_failure{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Add Attribute"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_create_failure{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Create"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_get_attributes_failure{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Get Attributes"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_modify_attribute_failure{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Modify Attribute"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_revoke_failure{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Revoke"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_delete_attribute_failure{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Delete Attribute"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_check_failure{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Check"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_get_attribute_list_failure{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Get Attribute List"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_get_failure{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Get Failure"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_locate_failure{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Locate"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_discover_versions_failure{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Discover Versions"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_activate_failure{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Activate"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_query_failure{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Query"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_destroy_failure{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Destroy"
    },
    {
     "expr": "sum(rate(ciphertrust_nae_kmip_register_failure{instance =~ \"$instances\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Register"
    }
   ]
  }
 ]
}