{
 "title": "CipherTrust Manager Developer",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instances", "label": "instances", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Average JWT Processing time",
   "type": "graph",
   "description": "This is a moving average, over each minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "rate(ciphertrust_api_jwt_middleware_processing_time_seconds_sum{instance =~ \"$instances\", service = \"api\"}[1m]) / rate(ciphertrust_api_jwt_middleware_processing_time_seconds_count{instance =~ \"$instances\", service = \"api\"}[1m])",
     "legendFormat": "{{instance}}, cache_hit: {{cache_hit}} "
    }
   ]
  },
  {
   "title": "Applications And Accounts Totals",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ciphertrust_authorization_applications_total{instance =~ \"$instances\", service = \"authorization\"}",
     "legendFormat": "{{instance}} / Applications"
    },
    {
     "expr": "ciphertrust_authorization_accounts_total{instance =~ \"$instances\", service = \"authorization\"}",
     "legendFormat": "{{instance}} / Accounts"
    }
   ]
  },
  {
   "title": "KEKs Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ciphertrust_key_vault_keks_total{instance =~ \"$instances\", service = \"key_vault\"}",
     "legendFormat": "{{instance}} / KEKs"
    }
   ]
  },
  {
   "title": "Authorization Policies Cache HIts per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ciphertrust_authorization_effective_policies_cache_hits{instance =~ \"$instances\"}[1m])  ",
     "legendFormat": "{{instance}} / Cache Hits"
    }
   ]
  },
  {
   "title": "Average Prometheus Metrics Scraping Response Time",
   "type": "timeseries",
   "description": "This is a moving average over an interval of one minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(http_response_time_seconds_sum{code=\"200\", instance =~ \"$instances\", method=\"GET\", path=\"/metrics/prometheus\"}[1m]) / rate(http_response_time_seconds_count{code=\"200\", instance =~ \"$instances\", method=\"GET\", path=\"/metrics/prometheus\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}