{
 "title": "CipherTrust Manager HTTP Traffic",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instances", "label": "instances", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average HTTP Response Time Per Minute",
   "type": "graph",
   "description": "This time series represents the average HTTP response time for each microservice in the CipherTrust Manager.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "(rate(http_response_time_seconds_sum{instance =~ \"$instances\", path !~ \"/metrics/prometheus\"}[1m]) / rate(http_response_time_seconds_count{instance =~ \"$instances\", path !~ \"/metrics/prometheus\"}[1m]))",
     "legendFormat": "{{instance}} / {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "HTTP Requests In The Last Minute",
   "type": "timeseries",
   "description": "Number of HTTP requests per minute over various methods/paths averaged over the last one minute.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(http_response_time_seconds_count{instance =~ \"$instances\"}[1m])",
     "legendFormat": "{{instance}} / {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Average CipherTrust Network Latency Per Minute",
   "type": "graph",
   "description": "This time series represents the network latency (in seconds) associated with HTTP requests processed by the CipherTrust Manager (CM). There is a time series for each microservice in the CM. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": " (rate(ciphertrust_httpclient_network_latency_seconds_sum{instance =~ \"$instances\"}[1m]) /  rate(ciphertrust_httpclient_network_latency_seconds_count{instance =~ \"$instances\"}[1m]))",
     "legendFormat": "{{instance}} / {{service}}->{{upstream_service}}"
    }
   ]
  },
  {
   "title": "Average CM HTTP Client Response Time Per Minute",
   "type": "graph",
   "description": "This time series represents the average HTTP response time for HTTP requests between CM services.  There is one time series for each source service.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "(rate(httpclient_response_time_seconds_sum{instance =~ \"$instances\"}[1m])) / (rate(httpclient_response_time_seconds_count{instance =~ \"$instances\"}[1m]))",
     "legendFormat": "{{instance}} / {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "HTTP 500 Errors In The Last Minute",
   "type": "timeseries",
   "description": "Number of HTTP requests per minute returning a 500 error over various methods/paths averaged over the last one minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(http_response_time_seconds_count{instance =~ \"$instances\", code = \"500\"}[1m])",
     "legendFormat": "{{instance}} / {{method}} {{path}}"
    }
   ]
  }
 ]
}