{
 "title": "CipherTrust Manager NAE Developer",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instances", "label": "instances", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "NAE Developer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Key Info Cache Misses Time Per Minute",
   "type": "timeseries",
   "description": "This time series represents the average number of misses per minute in the NAE Key Cache.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(ciphertrust_nae_key_info_cache_misses_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Key Info Cache Hits Time Per Minute",
   "type": "timeseries",
   "description": "This time series represents the average number of misses per minute in the NAE Key Cache.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(ciphertrust_nae_key_info_cache_hits_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "XML Total Processing time",
   "type": "timeseries",
   "description": "Total time in seconds needed to process a NAE XML request. This metric is disabled by default, and can be enabled using the NAE environmental variable ENABLE_DEBUG_METRICS.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(rate(ciphertrust_nae_xml_total_seconds_sum{instance =~ \"$instances\"}[1m]) / rate(ciphertrust_nae_xml_total_seconds_count{instance =~ \"$instances\"}[1m]))",
     "legendFormat": "{{instance}} / {{token}}"
    }
   ]
  },
  {
   "title": "XML Parsing Time",
   "type": "timeseries",
   "description": "Time to parse an XML request.  This metric is disabled by default, and can be enabled using the NAE environmental variable ENABLE_DEBUG_METRICS.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "(rate(ciphertrust_nae_xml_parse_seconds_sum{instance =~ \"$instances\"}[1m]) / rate(ciphertrust_nae_xml_parse_seconds_count{instance =~ \"$instances\"}[1m]))",
     "legendFormat": "{{instance}} / {{token}}"
    }
   ]
  },
  {
   "title": "XML Transmit Time",
   "type": "timeseries",
   "description": "Number of seconds needed to transmit an XML response.  This metric is disabled by default, and can be enabled using the NAE environmental variable ENABLE_DEBUG_METRICS.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(rate(ciphertrust_nae_xml_tx_seconds_sum{instance =~ \"$instances\"}[1m]) / rate(ciphertrust_nae_xml_tx_seconds_count{instance =~ \"$instances\"}[1m]))",
     "legendFormat": "{{instance}} / {{token}}"
    }
   ]
  },
  {
   "title": "XML Receive Time",
   "type": "timeseries",
   "description": "Number of seconds needed to receive a XML request.  This metric is disabled by default, and can be enabled using the NAE environmental variable ENABLE_DEBUG_METRICS.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "(rate(ciphertrust_nae_xml_rx_seconds_sum{instance =~ \"$instances\"}[1m]) / rate(ciphertrust_nae_xml_rx_seconds_count{instance =~ \"$instances\"}[1m]))",
     "legendFormat": "{{instance}} / {{token}}"
    }
   ]
  },
  {
   "title": "XML Execution Time",
   "type": "timeseries",
   "description": "Number of seconds needed to execute a XML command.  This metric is disabled by default, and can be enabled using the NAE environmental variable ENABLE_DEBUG_METRICS.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "(rate(ciphertrust_nae_xml_exec_seconds_sum{instance =~ \"$instances\"}[1m]) / rate(ciphertrust_nae_xml_exec_seconds_count{instance =~ \"$instances\"}[1m]))",
     "legendFormat": "{{instance}} / {{token}}"
    }
   ]
  }
 ]
}